/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class*/

#ifndef _Included_renrenkan_Md5Utils
#define _Included_renrenkan_Md5Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * Method:    getToken
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_renrenkan_Md5Utils_getToken
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
