/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_jfz_http_NativeHttp */

#ifndef _Included_jni_jfz_http_NativeHttp
#define _Included_jni_jfz_http_NativeHttp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_jfz_http_NativeHttp
 * Method:    getNative
 * Signature: (Ljava/lang/String;Ljni/jfz/http/NativeHttpCallback;)V
 */
JNIEXPORT void JNICALL Java_jni_jfz_http_NativeHttp_getNative
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
