/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_sdk_SdkNative */

#ifndef _Included_com_jni_sdk_SdkNative
#define _Included_com_jni_sdk_SdkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_sdk_SdkNative
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_sdk_SdkNative_getStr
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_sdk_SdkNative
 * Method:    updateValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_sdk_SdkNative_updateValue
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_sdk_SdkNative
 * Method:    onNativeConfig
 * Signature: (Lcom/jni/sdk/OnNativeConfig;)V
 */
JNIEXPORT void JNICALL Java_com_jni_sdk_SdkNative_onNativeConfig
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
